package online.yaqian.zhiqiunode.model;

// default package
// Generated 2016-5-2 0:16:53 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

/**
 * IdentifyCode generated by hbm2java
 */
@Entity
@Table(name = "identify_code", catalog = "zhiqiunode", uniqueConstraints = {
		@UniqueConstraint(columnNames = "identify_code"), @UniqueConstraint(columnNames = "vendor_id") })
@DynamicInsert(true)
@DynamicUpdate(true)
public class IdentifyCode implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1995893803933325313L;
	private Integer codeId;
	private int vendorId;
	private String identifyCode;
	private Date datetime;

	public IdentifyCode() {
	}

	public IdentifyCode(int vendorId, String identifyCode) {
		this.vendorId = vendorId;
		this.identifyCode = identifyCode;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "code_id", unique = true, nullable = false)
	public Integer getCodeId() {
		return this.codeId;
	}

	public void setCodeId(Integer codeId) {
		this.codeId = codeId;
	}

	@Column(name = "vendor_id", unique = true, nullable = false)
	public int getVendorId() {
		return this.vendorId;
	}

	public void setVendorId(int vendorId) {
		this.vendorId = vendorId;
	}

	@Column(name = "identify_code", unique = true, nullable = false, length = 5)
	public String getIdentifyCode() {
		return this.identifyCode;
	}

	public void setIdentifyCode(String identifyCode) {
		this.identifyCode = identifyCode;
	}


	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "datetime", updatable = false, length = 19)
	public Date getDatetime() {
		return this.datetime;
	}

	public void setDatetime(Date datetime) {
		this.datetime = datetime;
	}

}
