package online.yaqian.zhiqiunode.model;
// default package
// Generated 2016-4-14 0:47:51 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

/**
 * Mine generated by hbm2java
 */
@Entity
@Table(name = "mine", catalog = "zhiqiunode", uniqueConstraints = @UniqueConstraint(columnNames = { "isbn",
"user_id" }))
@DynamicInsert(true)
@DynamicUpdate(true)
public class Mine implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3571527615040213044L;
	private Integer mineId;
	private int userId;
	private String isbn;
	private String prefer;
	private Integer qty;
	private Date updateTime;

	public Mine() {
	}

	public Mine(int userId, String isbn, Date updateTime) {
		this.userId = userId;
		this.isbn = isbn;
		this.updateTime = updateTime;
	}

	public Mine(int userId, String isbn, String prefer, Integer qty, Date updateTime) {
		this.userId = userId;
		this.isbn = isbn;
		this.prefer = prefer;
		this.qty = qty;
		this.updateTime = updateTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "mine_id", unique = true, nullable = false)
	public Integer getMineId() {
		return this.mineId;
	}

	public void setMineId(Integer mineId) {
		this.mineId = mineId;
	}

	@Column(name = "user_id", nullable = false)
	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	@Column(name = "isbn", nullable = false, length = 13)
	public String getIsbn() {
		return this.isbn;
	}

	public void setIsbn(String isbn) {
		this.isbn = isbn;
	}

	@Column(name = "prefer", length = 45)
	public String getPrefer() {
		return this.prefer;
	}

	public void setPrefer(String prefer) {
		this.prefer = prefer;
	}

	@Column(name = "qty")
	public Integer getQty() {
		return this.qty;
	}

	public void setQty(Integer qty) {
		this.qty = qty;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_time", updatable = false, length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

}
