package online.yaqian.zhiqiunode.model;

// default package
// Generated 2016-5-2 0:16:53 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

/**
 * Order generated by hbm2java
 */
@Entity
@Table(name = "order", catalog = "zhiqiunode", uniqueConstraints = @UniqueConstraint(columnNames = { "vendor_id",
		"isbn", "vendee_id" }))
@DynamicInsert(true)
@DynamicUpdate(true)
public class Order implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7061250882001814036L;
	private Integer orderId;
	private int vendorId;
	private int vendeeId;
	private String isbn;
	private Integer qty;
	private Date datetime;

	public Order() {
	}

	public Order(int vendorId, int vendeeId, String isbn, Date datetime) {
		this.vendorId = vendorId;
		this.vendeeId = vendeeId;
		this.isbn = isbn;
		this.datetime = datetime;
	}

	public Order(int vendorId, int vendeeId, String isbn, Integer qty, Date datetime) {
		this.vendorId = vendorId;
		this.vendeeId = vendeeId;
		this.isbn = isbn;
		this.qty = qty;
		this.datetime = datetime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "order_id", unique = true, nullable = false)
	public Integer getOrderId() {
		return this.orderId;
	}

	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}

	@Column(name = "vendor_id", nullable = false)
	public int getVendorId() {
		return this.vendorId;
	}

	public void setVendorId(int vendorId) {
		this.vendorId = vendorId;
	}

	@Column(name = "vendee_id", nullable = false)
	public int getVendeeId() {
		return this.vendeeId;
	}

	public void setVendeeId(int vendeeId) {
		this.vendeeId = vendeeId;
	}

	@Column(name = "isbn", nullable = false, length = 13)
	public String getIsbn() {
		return this.isbn;
	}

	public void setIsbn(String isbn) {
		this.isbn = isbn;
	}

	@Column(name = "qty")
	public Integer getQty() {
		return this.qty;
	}

	public void setQty(Integer qty) {
		this.qty = qty;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "datetime", updatable = false, length = 19)
	public Date getDatetime() {
		return this.datetime;
	}

	public void setDatetime(Date datetime) {
		this.datetime = datetime;
	}

}
