package online.yaqian.zhiqiunode.model;
// default package
// Generated 2016-4-4 21:55:42 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

/**
 * UserProfile generated by hbm2java
 */
@Entity(name="UserProfile")
@Table(name = "user_profile", catalog = "zhiqiunode")
@DynamicInsert(true)
@DynamicUpdate(true)
public class UserProfile implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2501434518045237983L;
	private Integer profileId;
	private String email;
	private String keyWord;
	private String qqCode;
	private String phone;
	private String wechatId;
	private Date updateTime;

	public UserProfile() {
	}

	public UserProfile(String email, String keyWord, String qqCode, String phone, String wechatId) {
		this.email = email;
		this.keyWord = keyWord;
		this.qqCode = qqCode;
		this.phone = phone;
		this.wechatId = wechatId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "profile_id", unique = true, nullable = false)
	public Integer getProfileId() {
		return this.profileId;
	}

	public void setProfileId(Integer profileId) {
		this.profileId = profileId;
	}

	@Column(name = "email", length = 20)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "key_word", length = 20)
	public String getKeyWord() {
		return this.keyWord;
	}

	public void setKeyWord(String keyWord) {
		this.keyWord = keyWord;
	}

	@Column(name = "qq_code", length = 12)
	public String getQqCode() {
		return this.qqCode;
	}

	public void setQqCode(String qqCode) {
		this.qqCode = qqCode;
	}

	@Column(name = "phone", length = 11)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "wechat_id", length = 20)
	public String getWechatId() {
		return this.wechatId;
	}

	public void setWechatId(String wechatId) {
		this.wechatId = wechatId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_time", length = 19,updatable = false)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}


}
