package online.yaqian.zhiqiunode.model;


// Generated 2015-12-11 23:46:19 by Hibernate Tools 4.0.0

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import org.hibernate.annotations.GenericGenerator;


/**
 * Wechatuser generated by hbm2java
 */
@Entity(name="WechatUser")
@Table(name = "wechat_user", catalog = "zhiqiunode")
@DynamicInsert(true)
@DynamicUpdate(true)
public class WechatUser implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1L;

	private String openId;
	private Integer userId;
	private Date updateTime;
	private Boolean isActive;
	
	public WechatUser() {
	}

	public WechatUser(String openId) {
		this.openId = openId;
	}

	public WechatUser(String openId, Integer userId, Boolean isActive) {
		this.openId = openId;
		this.userId = userId;
		this.isActive = isActive;
	}

	@Id
	@GeneratedValue(generator ="assigned")
	@GenericGenerator(name ="assigned", strategy ="assigned")
	@Column(name = "open_id", unique = true, nullable = false, length = 28)
	public String getOpenId() {
		return this.openId;
	}

	public void setOpenId(String openId) {
		this.openId = openId;
	}

	@Column(name = "user_id")
	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_time", length = 19,updatable = false)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@Column(name = "is_active")
	public Boolean getIsActive() {
		return this.isActive;
	}

	public void setIsActive(Boolean isActive) {
		this.isActive = isActive;
	}
}
