package online.yaqian.zhiqiunode.util;

public class MajorUtil {
	
	public static final boolean validateShortMajorForm(String shortForm) {
		if (getMajor2Full(shortForm).equals("参数错误")) {
			return false;
		}
		return true;
	}
	
	public static final String getMajor2Full(String major) {
		switch (major) {
		case "aa":
			return "材料成型及控制工程";
		case "ab":
			return "材料成型及控制工程(3+2)";
		case "ac":
			return "测控技术与仪器";
		case "ad":
			return "测控技术与仪器(3+2)";
		case "ae":
			return "电气工程及其自动化";
		case "af":
			return "电气类";
		case "ag":
			return "工业工程";
		case "ah":
			return "过程装备与控制工程";
		case "ai":
			return "过程装备与控制工程(3+2)";
		case "aj":
			return "机械电子工程";
		case "ak":
			return "机械类";
		case "al":
			return "机械设计制造及其自动化";
		case "am":
			return "机械设计制造及其自动化(全英文)";
		case "an":
			return "自动化";

		case "ba":
			return "传播学";
		case "bb":
			return "汉语言文学";
		case "bc":
			return "汉语言文学(3+2)";

		case "ca":
			return "包装工程";
		case "cb":
			return "材料科学与工程";
		case "cc":
			return "材料类";
		case "cd":
			return "纺织工程";
		case "ce":
			return "纺织工程(3+2)";
		case "cf":
			return "纺织工程(卓越计划)";
		case "cg":
			return "纺织类";
		case "ch":
			return "纺织品设计";
		case "ci":
			return "非织造材料与工程";
		case "cj":
			return "轻化工程";
		case "ck":
			return "轻化工程(3+2)";
		case "cl":
			return "轻化工程(纺织贸易与检测全英文)";
		case "cm":
			return "轻化工程(染整工艺与设计)";
		case "cn":
			return "轻化工程(生态纺织化学品)";
		case "co":
			return "轻化工程(造纸方向)";
		case "cp":
			return "轻化工程(卓越计划)";

		case "fa":
			return "法学";
		case "fb":
			return "公共管理类";
		case "fc":
			return "公共事业管理";
		case "fd":
			return "公共事业管理(3+2)";
		case "fe":
			return "行政管理";
		case "ff":
			return "行政管理(3+2)";
		case "fg":
			return "社会工作";
		case "fh":
			return "社会工作(3+2)";

		case "ga":
			return "电子商务";
		case "gb":
			return "电子商务类";
		case "gc":
			return "工商管理";
		case "gd":
			return "工商管理(3+2)";
		case "ge":
			return "工商管理(全英文)";
		case "gf":
			return "工商管理类";
		case "gg":
			return "管理科学与工程类";
		case "gh":
			return "国际经济与贸易";
		case "gi":
			return "国际经济与贸易(全英文)";
		case "gj":
			return "会计学";
		case "gk":
			return "金融学";
		case "gl":
			return "经济统计学";
		case "gm":
			return "经济学";
		case "gn":
			return "经济与贸易类";
		case "go":
			return "人力资源管理";
		case "gp":
			return "市场营销";
		case "gq":
			return "统计学";
		case "gr":
			return "信息管理与信息系统";

		case "ja":
			return "风景园林";
		case "jb":
			return "风景园林(3+2)";
		case "jc":
			return "工程管理";
		case "jd":
			return "建筑环境与能源应用工程";
		case "je":
			return "建筑环境与能源应用工程(3+2)";
		case "jf":
			return "建筑环境与设备工程";
		case "jg":
			return "建筑学";
		case "jh":
			return "土木工程";

		case "la":
			return "材料化学";
		case "lb":
			return "化学类";
		case "lc":
			return "数学类";
		case "ld":
			return "数学与应用数学";
		case "le":
			return "信息与计算科学";
		case "lf":
			return "信息与计算科学(3+2)";
		case "lg":
			return "应用化学";
		case "lh":
			return "应用物理学";
		case "li":
			return "应用心理学";
		case "lj":
			return "应用心理学(3+2)";

		case "qa":
			return "材化生实验班";
		case "qb":
			return "机电实验班";
		case "qc":
			return "经济管理实验班";
		case "qd":
			return "理工实验班";
		case "qe":
			return "信息电子实验班";

		case "sa":
			return "生物技术";
		case "sb":
			return "生物技术(全英文)";
		case "sc":
			return "生物技术(生物工程)";
		case "sd":
			return "生物技术(生物制药)";
		case "se":
			return "生物制药";

		case "wa":
			return "日语";
		case "wb":
			return "英语";

		case "xa":
			return "电子信息工程";
		case "xb":
			return "电子信息科学与技术";
		case "xc":
			return "电子信息类";
		case "xd":
			return "计算机科学与技术";
		case "xe":
			return "计算机科学与技术(全英文)";
		case "xf":
			return "数字媒体技术";
		case "xg":
			return "通信工程";

		case "ya":
			return "产品设计";
		case "yb":
			return "动画";
		case "yc":
			return "工业设计";
		case "yd":
			return "广告学";
		case "ye":
			return "环境设计";
		case "yf":
			return "美术学";
		case "yg":
			return "设计学类";
		case "yh":
			return "视觉传达设计";
		case "yi":
			return "视觉传达设计(广告设计)";
		case "yj":
			return "艺术设计(产品设计)";
		case "yk":
			return "艺术设计(环境艺术设计)";
		case "yl":
			return "艺术设计(家具设计)";
		case "ym":
			return "艺术设计(视觉传达设计)";

		case "za":
			return "表演(人物形象设计)";
		case "zb":
			return "表演(时装表演艺术)";
		case "zc":
			return "产品设计(纺织品艺术设计)";
		case "zd":
			return "服装设计与工程";
		case "ze":
			return "服装设计与工程(全英文)";
		case "zf":
			return "服装设计与工程(中美合作)";
		case "zg":
			return "服装设计与工程(卓越计划)";
		case "zh":
			return "服装与服饰设计";
		case "zi":
			return "服装与服饰设计(服饰品设计)";
		case "zj":
			return "服装与服饰设计(服装设计中美合作 )";
		case "zk":
			return "服装与服饰设计(服装艺术设计)";
		case "zl":
			return "服装与服饰设计(人物形象设计)";
		case "zm":
			return "服装与服饰设计(设计与营销)";
		case "zn":
			return "服装与服饰设计(设计与营销)(3+2)";
		case "zo":
			return "服装与服饰设计(设计与营销中美合作)";
		case "zp":
			return "艺术设计(服饰品设计与营销)";
		case "zq":
			return "艺术设计(服装设计中美合作)";
		case "zr":
			return "艺术设计(服装艺术设计)";
		case "zs":
			return "艺术设计(染织艺术设计)";
		case "zt":
			return "艺术设计(人物造型)";
		case "zu":
			return "艺术设计(人物造型设计)";
		case "zv":
			return "艺术设计(设计与营销中美合作)";
		case "zw":
			return "艺术设计(时装表演及营销)";
			
		case "pp":
			return "其它专业";

		default:
			return "参数错误";
		}

	}

	public static final String getMajor2Short(String major) {
		switch (major) {
		case "材料成型及控制工程":
			return "aa";
		case "材料成型及控制工程(3+2)":
			return "ab";
		case "测控技术与仪器":
			return "ac";
		case "测控技术与仪器(3+2)":
			return "ad";
		case "电气工程及其自动化":
			return "ae";
		case "电气类":
			return "af";
		case "工业工程":
			return "ag";
		case "过程装备与控制工程":
			return "ah";
		case "过程装备与控制工程(3+2)":
			return "ai";
		case "机械电子工程":
			return "aj";
		case "机械类":
			return "ak";
		case "机械设计制造及其自动化":
			return "al";
		case "机械设计制造及其自动化(全英文)":
			return "am";
		case "自动化":
			return "an";

		case "传播学":
			return "ba";
		case "汉语言文学":
			return "bb";
		case "汉语言文学(3+2)":
			return "bc";

		case "包装工程":
			return "ca";
		case "材料科学与工程":
			return "cb";
		case "材料类":
			return "cc";
		case "纺织工程":
			return "cd";
		case "纺织工程(3+2)":
			return "ce";
		case "纺织工程(卓越计划)":
			return "cf";
		case "纺织类":
			return "cg";
		case "纺织品设计":
			return "ch";
		case "非织造材料与工程":
			return "ci";
		case "轻化工程":
			return "cj";
		case "轻化工程(3+2)":
			return "ck";
		case "轻化工程(纺织贸易与检测全英文)":
			return "cl";
		case "轻化工程(染整工艺与设计)":
			return "cm";
		case "轻化工程(生态纺织化学品)":
			return "cn";
		case "轻化工程(造纸方向)":
			return "co";
		case "轻化工程(卓越计划)":
			return "cp";

		case "法学":
			return "fa";
		case "公共管理类":
			return "fb";
		case "公共事业管理":
			return "fc";
		case "公共事业管理(3+2)":
			return "fd";
		case "行政管理":
			return "fe";
		case "行政管理(3+2)":
			return "ff";
		case "社会工作":
			return "fg";
		case "社会工作(3+2)":
			return "fh";

		case "电子商务":
			return "ga";
		case "电子商务类":
			return "gb";
		case "工商管理":
			return "gc";
		case "工商管理(3+2)":
			return "gd";
		case "工商管理(全英文)":
			return "ge";
		case "工商管理类":
			return "gf";
		case "管理科学与工程类":
			return "gg";
		case "国际经济与贸易":
			return "gh";
		case "国际经济与贸易(全英文)":
			return "gi";
		case "会计学":
			return "gj";
		case "金融学":
			return "gk";
		case "经济统计学":
			return "gl";
		case "经济学":
			return "gm";
		case "经济与贸易类":
			return "gn";
		case "人力资源管理":
			return "go";
		case "市场营销":
			return "gp";
		case "统计学":
			return "gq";
		case "信息管理与信息系统":
			return "gr";

		case "材料化学":
			return "la";
		case "化学类":
			return "lb";
		case "数学类":
			return "lc";
		case "数学与应用数学":
			return "ld";
		case "信息与计算科学":
			return "le";
		case "信息与计算科学(3+2)":
			return "lf";
		case "应用化学":
			return "lg";
		case "应用物理学":
			return "lh";
		case "应用心理学":
			return "li";
		case "应用心理学(3+2)":
			return "lj";

		case "风景园林":
			return "ja";
		case "风景园林(3+2)":
			return "jb";
		case "工程管理":
			return "jc";
		case "建筑环境与能源应用工程":
			return "jd";
		case "建筑环境与能源应用工程(3+2)":
			return "je";
		case "建筑环境与设备工程":
			return "jf";
		case "建筑学":
			return "jg";
		case "土木工程":
			return "jh";

		case "材化生实验班":
			return "qa";
		case "机电实验班":
			return "qb";
		case "经济管理实验班":
			return "qc";
		case "理工实验班":
			return "qd";
		case "信息电子实验班":
			return "qe";

		case "生物技术":
			return "sa";
		case "生物技术(全英文)":
			return "sb";
		case "生物技术(生物工程)":
			return "sc";
		case "生物技术(生物制药)":
			return "sd";
		case "生物制药":
			return "se";

		case "日语":
			return "wa";
		case "英语":
			return "wb";
	
		case "电子信息工程":
			return "xa";
		case "电子信息科学与技术":
			return "xb";
		case "电子信息类":
			return "xc";
		case "计算机科学与技术":
			return "xd";
		case "计算机科学与技术(全英文)":
			return "xe";
		case "数字媒体技术":
			return "xf";
		case "通信工程":
			return "xg";

		case "产品设计":
			return "ya";
		case "动画":
			return "yb";
		case "工业设计":
			return "yc";
		case "广告学":
			return "yd";
		case "环境设计":
			return "ye";
		case "美术学":
			return "yf";
		case "设计学类":
			return "yg";
		case "视觉传达设计":
			return "yh";
		case "视觉传达设计(广告设计)":
			return "yi";
		case "艺术设计(产品设计)":
			return "yj";
		case "艺术设计(环境艺术设计)":
			return "yk";
		case "艺术设计(家具设计)":
			return "yl";
		case "艺术设计(视觉传达设计)":
			return "ym";

		case "表演(人物形象设计)":
			return "za";
		case "表演(时装表演艺术)":
			return "zb";
		case "产品设计(纺织品艺术设计)":
			return "zc";
		case "服装设计与工程":
			return "zd";
		case "服装设计与工程(全英文)":
			return "ze";
		case "服装设计与工程(中美合作)":
			return "zf";
		case "服装设计与工程(卓越计划)":
			return "zg";
		case "服装与服饰设计":
			return "zh";
		case "服装与服饰设计(服饰品设计)":
			return "zi";
		case "服装与服饰设计(服装设计中美合作 )":
			return "zj";
		case "服装与服饰设计(服装艺术设计)":
			return "zk";
		case "服装与服饰设计(人物形象设计)":
			return "zl";
		case "服装与服饰设计(设计与营销)":
			return "zm";
		case "服装与服饰设计(设计与营销)(3+2)":
			return "zn";
		case "服装与服饰设计(设计与营销中美合作)":
			return "zo";
		case "艺术设计(服饰品设计与营销)":
			return "zp";
		case "艺术设计(服装设计中美合作)":
			return "zq";
		case "艺术设计(服装艺术设计)":
			return "zr";
		case "艺术设计(染织艺术设计)":
			return "zs";
		case "艺术设计(人物造型)":
			return "zt";
		case "艺术设计(人物造型设计)":
			return "zu";
		case "艺术设计(设计与营销中美合作)":
			return "zv";
		case "艺术设计(时装表演及营销)":
			return "zw";

		default:
			return "pp";// 其它专业

		}
	}

}
